### ISSUE TITLE
[PE-D][Tester B] AssignT can overwrite previous assigned person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T08-3/tp#215] opened 2023-11-03 21:20 UTC
AssignT can override assigned people to a task. Perhaps introduce a flag (like -f) to force the replacement of someone on a task?

Steps to reproduce:
1. Create a project
2. Create a task
3. Assign someone to this task
4. Assign someone else to this task using AssignT.

The first person will be kicked out of the Task!

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SungMatt/ped#6

**Comment by rayyan35p** [comment] 2023-11-09 03:26
Actually, this is part of the intended behaviour for assigning employees to tasks. Each task should only hold one employee so assigning a new employee to a task that has already been assigned to someone else should replace that employee with the new one. However, the behaviour that tasks can only hold one employee was not specified in the UG leading to this issue. We will be adding a remark to the UG to inform users that tasks can only hold one employee.

**Closed** 2023-11-10 02:39 UTC
Labels: type.Documentation, ped.NotAllowed
